#!/bin/bash
export JAVA_HOME=${OPENSHIFT_DATA_DIR}jdk1.8.0_121
export TOMCAT_HOME=${OPENSHIFT_DATA_DIR}apache-tomcat-8.5.13
export M2_HOME=${OPENSHIFT_DATA_DIR}apache-maven-3.5.0
export PATH=$JAVA_HOME/bin:$M2_HOME/bin:$PATH

# clean up the build folder (to save disk space)
cd $OPENSHIFT_REPO_DIR
mvn --global-settings ${OPENSHIFT_DATA_DIR}maven.xml --file leslie/pom.xml clean
